// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: System.proto

package com.zero.example.protobuf;

public final class SystemPro {
  private SystemPro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SC_GlobleErrorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 errorMessageKey = 1;
    /**
     * <code>required int32 errorMessageKey = 1;</code>
     *
     * <pre>
     *全局异常id
     * </pre>
     */
    boolean hasErrorMessageKey();
    /**
     * <code>required int32 errorMessageKey = 1;</code>
     *
     * <pre>
     *全局异常id
     * </pre>
     */
    int getErrorMessageKey();

    // required int32 level = 2;
    /**
     * <code>required int32 level = 2;</code>
     *
     * <pre>
     *异常错误等级
     * </pre>
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 2;</code>
     *
     * <pre>
     *异常错误等级
     * </pre>
     */
    int getLevel();

    // optional string desc = 3;
    /**
     * <code>optional string desc = 3;</code>
     *
     * <pre>
     *错误描述
     * </pre>
     */
    boolean hasDesc();
    /**
     * <code>optional string desc = 3;</code>
     *
     * <pre>
     *错误描述
     * </pre>
     */
    java.lang.String getDesc();
    /**
     * <code>optional string desc = 3;</code>
     *
     * <pre>
     *错误描述
     * </pre>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    // optional string errorType = 4;
    /**
     * <code>optional string errorType = 4;</code>
     *
     * <pre>
     *判断同一错误发生在不同位置，类别内容为错误发生位置正常运行时的协议名称（例:SC_SkillSuddenEnlightenment）
     * </pre>
     */
    boolean hasErrorType();
    /**
     * <code>optional string errorType = 4;</code>
     *
     * <pre>
     *判断同一错误发生在不同位置，类别内容为错误发生位置正常运行时的协议名称（例:SC_SkillSuddenEnlightenment）
     * </pre>
     */
    java.lang.String getErrorType();
    /**
     * <code>optional string errorType = 4;</code>
     *
     * <pre>
     *判断同一错误发生在不同位置，类别内容为错误发生位置正常运行时的协议名称（例:SC_SkillSuddenEnlightenment）
     * </pre>
     */
    com.google.protobuf.ByteString
        getErrorTypeBytes();
  }
  /**
   * Protobuf type {@code SC_GlobleError}
   */
  public static final class SC_GlobleError extends
      com.google.protobuf.GeneratedMessage
      implements SC_GlobleErrorOrBuilder {
    // Use SC_GlobleError.newBuilder() to construct.
    private SC_GlobleError(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SC_GlobleError(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SC_GlobleError defaultInstance;
    public static SC_GlobleError getDefaultInstance() {
      return defaultInstance;
    }

    public SC_GlobleError getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SC_GlobleError(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              errorMessageKey_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              level_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              desc_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              errorType_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zero.example.protobuf.SystemPro.internal_static_SC_GlobleError_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zero.example.protobuf.SystemPro.internal_static_SC_GlobleError_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zero.example.protobuf.SystemPro.SC_GlobleError.class, com.zero.example.protobuf.SystemPro.SC_GlobleError.Builder.class);
    }

    public static com.google.protobuf.Parser<SC_GlobleError> PARSER =
        new com.google.protobuf.AbstractParser<SC_GlobleError>() {
      public SC_GlobleError parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SC_GlobleError(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SC_GlobleError> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 errorMessageKey = 1;
    public static final int ERRORMESSAGEKEY_FIELD_NUMBER = 1;
    private int errorMessageKey_;
    /**
     * <code>required int32 errorMessageKey = 1;</code>
     *
     * <pre>
     *全局异常id
     * </pre>
     */
    public boolean hasErrorMessageKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 errorMessageKey = 1;</code>
     *
     * <pre>
     *全局异常id
     * </pre>
     */
    public int getErrorMessageKey() {
      return errorMessageKey_;
    }

    // required int32 level = 2;
    public static final int LEVEL_FIELD_NUMBER = 2;
    private int level_;
    /**
     * <code>required int32 level = 2;</code>
     *
     * <pre>
     *异常错误等级
     * </pre>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 level = 2;</code>
     *
     * <pre>
     *异常错误等级
     * </pre>
     */
    public int getLevel() {
      return level_;
    }

    // optional string desc = 3;
    public static final int DESC_FIELD_NUMBER = 3;
    private java.lang.Object desc_;
    /**
     * <code>optional string desc = 3;</code>
     *
     * <pre>
     *错误描述
     * </pre>
     */
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string desc = 3;</code>
     *
     * <pre>
     *错误描述
     * </pre>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          desc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string desc = 3;</code>
     *
     * <pre>
     *错误描述
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string errorType = 4;
    public static final int ERRORTYPE_FIELD_NUMBER = 4;
    private java.lang.Object errorType_;
    /**
     * <code>optional string errorType = 4;</code>
     *
     * <pre>
     *判断同一错误发生在不同位置，类别内容为错误发生位置正常运行时的协议名称（例:SC_SkillSuddenEnlightenment）
     * </pre>
     */
    public boolean hasErrorType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string errorType = 4;</code>
     *
     * <pre>
     *判断同一错误发生在不同位置，类别内容为错误发生位置正常运行时的协议名称（例:SC_SkillSuddenEnlightenment）
     * </pre>
     */
    public java.lang.String getErrorType() {
      java.lang.Object ref = errorType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorType = 4;</code>
     *
     * <pre>
     *判断同一错误发生在不同位置，类别内容为错误发生位置正常运行时的协议名称（例:SC_SkillSuddenEnlightenment）
     * </pre>
     */
    public com.google.protobuf.ByteString
        getErrorTypeBytes() {
      java.lang.Object ref = errorType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      errorMessageKey_ = 0;
      level_ = 0;
      desc_ = "";
      errorType_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasErrorMessageKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, errorMessageKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, level_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getErrorTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorMessageKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, level_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getErrorTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zero.example.protobuf.SystemPro.SC_GlobleError parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zero.example.protobuf.SystemPro.SC_GlobleError parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zero.example.protobuf.SystemPro.SC_GlobleError parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zero.example.protobuf.SystemPro.SC_GlobleError parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zero.example.protobuf.SystemPro.SC_GlobleError parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zero.example.protobuf.SystemPro.SC_GlobleError parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zero.example.protobuf.SystemPro.SC_GlobleError parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zero.example.protobuf.SystemPro.SC_GlobleError parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zero.example.protobuf.SystemPro.SC_GlobleError parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zero.example.protobuf.SystemPro.SC_GlobleError parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zero.example.protobuf.SystemPro.SC_GlobleError prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SC_GlobleError}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zero.example.protobuf.SystemPro.SC_GlobleErrorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zero.example.protobuf.SystemPro.internal_static_SC_GlobleError_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zero.example.protobuf.SystemPro.internal_static_SC_GlobleError_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zero.example.protobuf.SystemPro.SC_GlobleError.class, com.zero.example.protobuf.SystemPro.SC_GlobleError.Builder.class);
      }

      // Construct using com.zero.example.protobuf.SystemPro.SC_GlobleError.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        errorMessageKey_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        errorType_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zero.example.protobuf.SystemPro.internal_static_SC_GlobleError_descriptor;
      }

      public com.zero.example.protobuf.SystemPro.SC_GlobleError getDefaultInstanceForType() {
        return com.zero.example.protobuf.SystemPro.SC_GlobleError.getDefaultInstance();
      }

      public com.zero.example.protobuf.SystemPro.SC_GlobleError build() {
        com.zero.example.protobuf.SystemPro.SC_GlobleError result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zero.example.protobuf.SystemPro.SC_GlobleError buildPartial() {
        com.zero.example.protobuf.SystemPro.SC_GlobleError result = new com.zero.example.protobuf.SystemPro.SC_GlobleError(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorMessageKey_ = errorMessageKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.desc_ = desc_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.errorType_ = errorType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zero.example.protobuf.SystemPro.SC_GlobleError) {
          return mergeFrom((com.zero.example.protobuf.SystemPro.SC_GlobleError)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zero.example.protobuf.SystemPro.SC_GlobleError other) {
        if (other == com.zero.example.protobuf.SystemPro.SC_GlobleError.getDefaultInstance()) return this;
        if (other.hasErrorMessageKey()) {
          setErrorMessageKey(other.getErrorMessageKey());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasDesc()) {
          bitField0_ |= 0x00000004;
          desc_ = other.desc_;
          onChanged();
        }
        if (other.hasErrorType()) {
          bitField0_ |= 0x00000008;
          errorType_ = other.errorType_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasErrorMessageKey()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zero.example.protobuf.SystemPro.SC_GlobleError parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zero.example.protobuf.SystemPro.SC_GlobleError) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 errorMessageKey = 1;
      private int errorMessageKey_ ;
      /**
       * <code>required int32 errorMessageKey = 1;</code>
       *
       * <pre>
       *全局异常id
       * </pre>
       */
      public boolean hasErrorMessageKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 errorMessageKey = 1;</code>
       *
       * <pre>
       *全局异常id
       * </pre>
       */
      public int getErrorMessageKey() {
        return errorMessageKey_;
      }
      /**
       * <code>required int32 errorMessageKey = 1;</code>
       *
       * <pre>
       *全局异常id
       * </pre>
       */
      public Builder setErrorMessageKey(int value) {
        bitField0_ |= 0x00000001;
        errorMessageKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 errorMessageKey = 1;</code>
       *
       * <pre>
       *全局异常id
       * </pre>
       */
      public Builder clearErrorMessageKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorMessageKey_ = 0;
        onChanged();
        return this;
      }

      // required int32 level = 2;
      private int level_ ;
      /**
       * <code>required int32 level = 2;</code>
       *
       * <pre>
       *异常错误等级
       * </pre>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 level = 2;</code>
       *
       * <pre>
       *异常错误等级
       * </pre>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 2;</code>
       *
       * <pre>
       *异常错误等级
       * </pre>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000002;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 2;</code>
       *
       * <pre>
       *异常错误等级
       * </pre>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0;
        onChanged();
        return this;
      }

      // optional string desc = 3;
      private java.lang.Object desc_ = "";
      /**
       * <code>optional string desc = 3;</code>
       *
       * <pre>
       *错误描述
       * </pre>
       */
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string desc = 3;</code>
       *
       * <pre>
       *错误描述
       * </pre>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string desc = 3;</code>
       *
       * <pre>
       *错误描述
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string desc = 3;</code>
       *
       * <pre>
       *错误描述
       * </pre>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 3;</code>
       *
       * <pre>
       *错误描述
       * </pre>
       */
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000004);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 3;</code>
       *
       * <pre>
       *错误描述
       * </pre>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        desc_ = value;
        onChanged();
        return this;
      }

      // optional string errorType = 4;
      private java.lang.Object errorType_ = "";
      /**
       * <code>optional string errorType = 4;</code>
       *
       * <pre>
       *判断同一错误发生在不同位置，类别内容为错误发生位置正常运行时的协议名称（例:SC_SkillSuddenEnlightenment）
       * </pre>
       */
      public boolean hasErrorType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string errorType = 4;</code>
       *
       * <pre>
       *判断同一错误发生在不同位置，类别内容为错误发生位置正常运行时的协议名称（例:SC_SkillSuddenEnlightenment）
       * </pre>
       */
      public java.lang.String getErrorType() {
        java.lang.Object ref = errorType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          errorType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorType = 4;</code>
       *
       * <pre>
       *判断同一错误发生在不同位置，类别内容为错误发生位置正常运行时的协议名称（例:SC_SkillSuddenEnlightenment）
       * </pre>
       */
      public com.google.protobuf.ByteString
          getErrorTypeBytes() {
        java.lang.Object ref = errorType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorType = 4;</code>
       *
       * <pre>
       *判断同一错误发生在不同位置，类别内容为错误发生位置正常运行时的协议名称（例:SC_SkillSuddenEnlightenment）
       * </pre>
       */
      public Builder setErrorType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        errorType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorType = 4;</code>
       *
       * <pre>
       *判断同一错误发生在不同位置，类别内容为错误发生位置正常运行时的协议名称（例:SC_SkillSuddenEnlightenment）
       * </pre>
       */
      public Builder clearErrorType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        errorType_ = getDefaultInstance().getErrorType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorType = 4;</code>
       *
       * <pre>
       *判断同一错误发生在不同位置，类别内容为错误发生位置正常运行时的协议名称（例:SC_SkillSuddenEnlightenment）
       * </pre>
       */
      public Builder setErrorTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        errorType_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SC_GlobleError)
    }

    static {
      defaultInstance = new SC_GlobleError(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SC_GlobleError)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SC_GlobleError_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SC_GlobleError_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014System.proto\"Y\n\016SC_GlobleError\022\027\n\017erro" +
      "rMessageKey\030\001 \002(\005\022\r\n\005level\030\002 \002(\005\022\014\n\004desc" +
      "\030\003 \001(\t\022\021\n\terrorType\030\004 \001(\tB&\n\031com.zero.ex" +
      "ample.protobufB\tSystemPro"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SC_GlobleError_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SC_GlobleError_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SC_GlobleError_descriptor,
              new java.lang.String[] { "ErrorMessageKey", "Level", "Desc", "ErrorType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
