// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageStructure.proto

package com.avalon.core.message;

public final class MessageStructure {
  private MessageStructure() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code messageType}
   */
  public enum messageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NORMAL = 0;</code>
     */
    NORMAL(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NORMAL = 0;</code>
     */
    public static final int NORMAL_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static messageType valueOf(int value) {
      return forNumber(value);
    }

    public static messageType forNumber(int value) {
      switch (value) {
        case 0: return NORMAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<messageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        messageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<messageType>() {
            public messageType findValueByNumber(int number) {
              return messageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.avalon.core.message.MessageStructure.getDescriptor().getEnumTypes().get(0);
    }

    private static final messageType[] VALUES = values();

    public static messageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private messageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:messageType)
  }

  public interface AvalonMessageSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AvalonMessageS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .messageType name = 1;</code>
     */
    int getNameValue();
    /**
     * <code>optional .messageType name = 1;</code>
     */
    com.avalon.core.message.MessageStructure.messageType getName();

    /**
     * <code>optional bytes messageStruct = 2;</code>
     */
    com.google.protobuf.ByteString getMessageStruct();
  }
  /**
   * Protobuf type {@code AvalonMessageS}
   */
  public  static final class AvalonMessageS extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:AvalonMessageS)
      AvalonMessageSOrBuilder {
    // Use AvalonMessageS.newBuilder() to construct.
    private AvalonMessageS(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AvalonMessageS() {
      name_ = 0;
      messageStruct_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AvalonMessageS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              name_ = rawValue;
              break;
            }
            case 18: {

              messageStruct_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.avalon.core.message.MessageStructure.internal_static_AvalonMessageS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.avalon.core.message.MessageStructure.internal_static_AvalonMessageS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.avalon.core.message.MessageStructure.AvalonMessageS.class, com.avalon.core.message.MessageStructure.AvalonMessageS.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private int name_;
    /**
     * <code>optional .messageType name = 1;</code>
     */
    public int getNameValue() {
      return name_;
    }
    /**
     * <code>optional .messageType name = 1;</code>
     */
    public com.avalon.core.message.MessageStructure.messageType getName() {
      com.avalon.core.message.MessageStructure.messageType result = com.avalon.core.message.MessageStructure.messageType.forNumber(name_);
      return result == null ? com.avalon.core.message.MessageStructure.messageType.UNRECOGNIZED : result;
    }

    public static final int MESSAGESTRUCT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString messageStruct_;
    /**
     * <code>optional bytes messageStruct = 2;</code>
     */
    public com.google.protobuf.ByteString getMessageStruct() {
      return messageStruct_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (name_ != com.avalon.core.message.MessageStructure.messageType.NORMAL.getNumber()) {
        output.writeEnum(1, name_);
      }
      if (!messageStruct_.isEmpty()) {
        output.writeBytes(2, messageStruct_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (name_ != com.avalon.core.message.MessageStructure.messageType.NORMAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, name_);
      }
      if (!messageStruct_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, messageStruct_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.avalon.core.message.MessageStructure.AvalonMessageS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.avalon.core.message.MessageStructure.AvalonMessageS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.avalon.core.message.MessageStructure.AvalonMessageS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.avalon.core.message.MessageStructure.AvalonMessageS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.avalon.core.message.MessageStructure.AvalonMessageS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.avalon.core.message.MessageStructure.AvalonMessageS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.avalon.core.message.MessageStructure.AvalonMessageS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.avalon.core.message.MessageStructure.AvalonMessageS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.avalon.core.message.MessageStructure.AvalonMessageS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.avalon.core.message.MessageStructure.AvalonMessageS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.avalon.core.message.MessageStructure.AvalonMessageS prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AvalonMessageS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AvalonMessageS)
        com.avalon.core.message.MessageStructure.AvalonMessageSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.avalon.core.message.MessageStructure.internal_static_AvalonMessageS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.avalon.core.message.MessageStructure.internal_static_AvalonMessageS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.avalon.core.message.MessageStructure.AvalonMessageS.class, com.avalon.core.message.MessageStructure.AvalonMessageS.Builder.class);
      }

      // Construct using com.avalon.core.message.MessageStructure.AvalonMessageS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = 0;

        messageStruct_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.avalon.core.message.MessageStructure.internal_static_AvalonMessageS_descriptor;
      }

      public com.avalon.core.message.MessageStructure.AvalonMessageS getDefaultInstanceForType() {
        return com.avalon.core.message.MessageStructure.AvalonMessageS.getDefaultInstance();
      }

      public com.avalon.core.message.MessageStructure.AvalonMessageS build() {
        com.avalon.core.message.MessageStructure.AvalonMessageS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.avalon.core.message.MessageStructure.AvalonMessageS buildPartial() {
        com.avalon.core.message.MessageStructure.AvalonMessageS result = new com.avalon.core.message.MessageStructure.AvalonMessageS(this);
        result.name_ = name_;
        result.messageStruct_ = messageStruct_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.avalon.core.message.MessageStructure.AvalonMessageS) {
          return mergeFrom((com.avalon.core.message.MessageStructure.AvalonMessageS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.avalon.core.message.MessageStructure.AvalonMessageS other) {
        if (other == com.avalon.core.message.MessageStructure.AvalonMessageS.getDefaultInstance()) return this;
        if (other.name_ != 0) {
          setNameValue(other.getNameValue());
        }
        if (other.getMessageStruct() != com.google.protobuf.ByteString.EMPTY) {
          setMessageStruct(other.getMessageStruct());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.avalon.core.message.MessageStructure.AvalonMessageS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.avalon.core.message.MessageStructure.AvalonMessageS) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int name_ = 0;
      /**
       * <code>optional .messageType name = 1;</code>
       */
      public int getNameValue() {
        return name_;
      }
      /**
       * <code>optional .messageType name = 1;</code>
       */
      public Builder setNameValue(int value) {
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .messageType name = 1;</code>
       */
      public com.avalon.core.message.MessageStructure.messageType getName() {
        com.avalon.core.message.MessageStructure.messageType result = com.avalon.core.message.MessageStructure.messageType.forNumber(name_);
        return result == null ? com.avalon.core.message.MessageStructure.messageType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .messageType name = 1;</code>
       */
      public Builder setName(com.avalon.core.message.MessageStructure.messageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        name_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .messageType name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString messageStruct_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes messageStruct = 2;</code>
       */
      public com.google.protobuf.ByteString getMessageStruct() {
        return messageStruct_;
      }
      /**
       * <code>optional bytes messageStruct = 2;</code>
       */
      public Builder setMessageStruct(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageStruct_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes messageStruct = 2;</code>
       */
      public Builder clearMessageStruct() {
        
        messageStruct_ = getDefaultInstance().getMessageStruct();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AvalonMessageS)
    }

    // @@protoc_insertion_point(class_scope:AvalonMessageS)
    private static final com.avalon.core.message.MessageStructure.AvalonMessageS DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.avalon.core.message.MessageStructure.AvalonMessageS();
    }

    public static com.avalon.core.message.MessageStructure.AvalonMessageS getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AvalonMessageS>
        PARSER = new com.google.protobuf.AbstractParser<AvalonMessageS>() {
      public AvalonMessageS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AvalonMessageS(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AvalonMessageS> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AvalonMessageS> getParserForType() {
      return PARSER;
    }

    public com.avalon.core.message.MessageStructure.AvalonMessageS getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AvalonMessageS_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AvalonMessageS_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026MessageStructure.proto\"C\n\016AvalonMessag" +
      "eS\022\032\n\004name\030\001 \001(\0162\014.messageType\022\025\n\rmessag" +
      "eStruct\030\002 \001(\014*\031\n\013messageType\022\n\n\006NORMAL\020\000" +
      "B+\n\027com.avalon.core.messageB\020MessageStru" +
      "ctureb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AvalonMessageS_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AvalonMessageS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AvalonMessageS_descriptor,
        new java.lang.String[] { "Name", "MessageStruct", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
