/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zero' at '16-6-13 下午5:03' with Gradle 2.6
 *
 * @author zero, @date 16-6-13 下午5:03
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
